remove padend dependency
mysticatea/npm-run-all pull request #242
Opened 2022-09-04 18:15 UTC by Pomax

This replaces the use of the string.prototype.padend dependency with the normal String.padEnd function, removing the need for 3.3Mb of dependencies.

2022-09-04 19:30 UTC, zloirock requested changes
It seems also need to bump `node` in `engines` field to 8 and remove `node` less than 8 from `.travis.yml`.

2022-09-04 23:53 UTC, Pomax commented
good point, bumped up to the older still-in-support Node versions and updated travis to test only the still supported (lts) versions of Node.

2022-10-16 23:30 UTC, leumasme commented
Wondered about this as well after investigating useless packages like is-bigint in my node_modules.
I dont believe that this would be the correct way, however. At the very least, it would be a breaking change and require a major version bump.
Perhaps just adding a tiny selfwritten padEnd implementation here is a better idea? I don't think dropping support just for the sake of not supporting out-of-date node versions is useful.

2022-10-17 03:48 UTC, Pomax commented
No it wouldn't? It only changes internal code, not an external API or something.

2023-01-11 23:01 UTC, jimmywarting commented
👍 lgtm, would be nice to get rid of all those sub dependencies

---

it's fine to to a minor release as long as you bump the `engines.node` accordingly to the nodejs version that supports native pad. The node version in package.json will safe guard against this kind of changes and just install the version that are most suitable for the node version that you have installed.

(have a old nodejs version installed? then it will install an older release)

Really the only time that it requires a major release is when your public api changes and you can't use the same code you have already been using

2023-01-11 23:02 UTC, jimmywarting approved these changes

2023-02-25 10:22 UTC, M00TSDNS commented
@mysticatea tech debt PR, please review+merge if you can

2023-02-28 13:23 UTC, Lucienest commented
this project seems to have abandoned

2023-02-28 13:43 UTC, M00TSDNS commented
Hi Toru,
There's a PR to slim down npm-run-all significantly over at mysticatea/npm-run-all#242<https://github.com/mysticatea/npm-run-all/pull/242>.
Please review when you get a chance! (Again this could be 1 week, 1 month or any amount of time.)

________________________________
From: Lucien Nocelli ***@***.***>
Sent: 28 February 2023 13:23
To: mysticatea/npm-run-all ***@***.***>
Cc: M00TSDNS ***@***.***>; Comment ***@***.***>
Subject: Re: [mysticatea/npm-run-all] remove padend dependency (PR #242)


this project seems to have abandoned

—
Reply to this email directly, view it on GitHub<https://github.com/mysticatea/npm-run-all/pull/242#issuecomment-1448173995>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5MVIFXFH5RGJHVAMPEWHUTWZX34FANCNFSM6AAAAAAQENSUVM>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-03-22 17:25 UTC, Pomax commented
No eyes on this in over 6 months: I'm going to assume that you're not interested in PRs, @mysticatea, and I don't want to see this clog up my outstanding PR list going forward. Feel free to reopen and merge in if you're still going to have a look.

2023-03-22 17:25 UTC, closed without merging

2023-03-23 19:28 UTC, Lucienest commented
the owner of this repo is still active but abandoned this project, no update since 2019, pathetic
@Pomax

2023-03-23 19:38 UTC, M00TSDNS commented
please delete the last word... fwiw we can fork the package and publish this PR and all others

it would just be called `npm-run-all-more`

2023-03-31 08:51 UTC, Lucienest commented
> please delete the last word... fwiw we can fork the package and publish this PR and all others
> 
> it would just be called `npm-run-all-more`

what else should I say? that's the truth
The project got abandoned, we can fork for sure but 
that doesn't change the fact.

2023-03-31 10:58 UTC, jimmywarting commented
As a maintainer of other big open source projects i think it feels kind of hostile, unappreciated and unnecessary. 
When somebody say something negative, specially when someone puts hes heart and sole into building something free without earning anything but the communities love and respect back.

Negativity leads to developer to no longer wanting to maintain anything more for free.

By using a more neutral and factual tone, you can still convey the information without adding any negativity or judgment to it. It's important to remember that open source projects are often maintained by volunteers, and we should always show appreciation for their contributions, regardless of their level of activity or availability.

2023-03-31 11:52 UTC, M00TSDNS commented
This was going to be a dead (really "remummified zombie") npm ticket. But someone made an open-source solution. Their code and review work will always remain ~90% of the total project effort even if the community forks.